version: "3"
services:
    db:
        image: postgres:latest
        restart: always
        ports:
            - "5433:5433"
        environment:
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "password"
        volumes:
            - ./data:/var/lib/postgresql/data
