### Create
POST http://localhost:3000/user/create
content-type: application/json

{
  "username":"fff",
  "password":"test1234",
  "email":"test@test.com"
}

### GetUser
GET http://localhost:3000/user/getUser/test@test.com

### Update User
PUT http://localhost:3000/user/update/test@test.com
content-type:application/json

{
  "username":"fff2",
  "password":"test1234",
  "email":"test@test.com"
}

### Delete User
DELETE http://localhost:3000/user/delete/test@test.com