### Create
POST http://localhost:3000/auth/register
content-type: application/json

{
  "username":"aa2",
  "password":"12345",
  "email":"test4@test.com"
}
### login
POST http://localhost:3000/auth/login
content-type: application/json

{
  "password":"12345",
  "email":"test4@test.com"
}
### login2
POST http://localhost:3000/auth/login2
content-type: application/json

{
  "password":"12345",
  "email":"test4@test.com"
}
### Guard 테스트
GET http://localhost:3000/auth/test-guard